name: GS-runner
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.7
  - numpy==1.19.1
  - sqlalchemy==1.3.19
  - tqdm==4.28.1
  - pandas==0.25.3
  - scikit-learn==0.23.2
  - tensorflow==1.14.0
  - Keras==2.2.4

